#!/bin/bash

gpio mode 0 out
gpio mode 4 out
gpio mode 2 out
gpio mode 3 out


gpio write 0 0
gpio write 4 0
gpio write 2 0
gpio write 3 0

for (( a=0; a<=10; a++ )); do

gpio write 0 1
gpio write 4 0
gpio write 2 0
gpio write 3 0

gpio write 0 0
gpio write 4 1
gpio write 2 0
gpio write 3 0

gpio write 0 0
gpio write 4 0
gpio write 2 1
gpio write 3 0

gpio write 0 0
gpio write 4 0
gpio write 2 0
gpio write 3 1

done;

gpio write 0 0
gpio write 4 0
gpio write 2 0
gpio write 3 0

